# Generated by Django 5.1.4 on 2024-12-28 14:30

import django.db.models.deletion
from django.db import migrations, models

print("00002 migratios-2 file executed")


class Migration(migrations.Migration):

    dependencies = [
        ('DBOneToMany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='DBOneToMany.author')),
            ],
        ),
    ]
