# Generated by Django 5.1.4 on 2024-12-28 14:48

from django.db import migrations, models

print("00002 migratios-2 file executed")

class Migration(migrations.Migration):

    dependencies = [
        ('DBOneToMany', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(related_name='genres', to='DBOneToMany.book')),
            ],
        ),
    ]
